version: "3.8"

services:
  evolutionapi_mod:
    container_name: evolutionapi_mod
    build:
      context: .
      dockerfile: Dockerfile
    image: evolution-api:local-mod
    restart: unless-stopped
    volumes:
      - evolution_mod:/evolution/instances
    ports:
      - "127.0.0.1:8081:8080"
    networks:
      - reverse_proxy
    env_file:
      - .env
    expose:
      - "8080"

volumes:
  evolution_mod:

# Definição Global da Rede da Evolution
networks:
  reverse_proxy:
    external: true